baseURL = "https://www.base_url.com/"
title = "Author Name"
theme = "xmin"
languageCode = "en"
defaultContentLanguage = "en"

enableEmoji = true

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$", ".*test_*"]

[pagination]
  pagerSize = 6

[markup.highlight]
noClasses = false

[markup.goldmark.renderer]
unsafe = true

[params]
description = "Author Name's personal website"
email = "email@example.com"
footer = "&copy; [Author Name](https://github.com/author_name) 2024 -- {Year} | Powered by [Hugo](https://gohugo.io)"

[taxonomies]
category = "categories"
series = "series"
tag = "tags"
author = "authors"

[languages.en]
languageName = ":us:"

[[languages.en.menu.main]]
name = "Home"
weight = 1
url = ""

[[languages.en.menu.main]]
name = "About"
weight = 2
url = "about/"

[[languages.en.menu.main]]
name = "Posts"
weight = 3
url = "posts/"

[[languages.en.menu.main]]
name = "Tags"
weight = 4
url = "tags/"

[[languages.en.menu.main]]
name = "Contact Me"
weight = 5
url = "contact/"

[languages.pt-br]
languageName = ":brazil:"
title = "Author Name"

[languages.pt-br.params]
description = "Site pessoal de Author Name"

[[languages.pt-br.menu.main]]
name = "Início"
weight = 1
url = ""

[[languages.pt-br.menu.main]]
name = "Sobre"
weight = 2
url = "about/"

[[languages.pt-br.menu.main]]
name = "Publicações"
weight = 3
url = "posts/"

[[languages.pt-br.menu.main]]
name = "Tags"
weight = 4
url = "tags/"

[[languages.pt-br.menu.main]]
name = "Contato"
weight = 5
url = "contact/"
